
services:
  api:
    build: .
    ports:
      - "8434:8434"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./static:/app/static
      - ./scratch:/app/scratch
      - ./package.json:/app/package.json
      - ./CHANGELOG.md:/app/CHANGELOG.md
    environment:
      - TZ=Europe/Paris
      - HOST_DATA_DIR=${PWD}/data
    restart: unless-stopped
